project:
  type: website
  output-dir: docs

website:
  title: "Carly L. Brantner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - presentations.qmd
      - teaching.qmd
      - involvement.qmd
      - cv.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

