---
title: "Community"
---

I enjoy contributing to the broader biostatistical and health community. Please feel free to contact me if would like to learn more about any of the following roles or groups that I am a part of.

## Consulting Experience

-   **Research Scientist (Epidemiology/Data Science)**, [*Kynisca Innovation Hub*](https://kyniscainnovationhub.com/)*,* 2023 – present

## Leadership Roles

-   [**Council of Emerging and New Statisticians**](https://www.enar.org/meetings/spring2024/profdev/cens.cfm) **(CENS) Member,** *ENAR of International Biometrics Society,* 2023 – present\
    Current Steering Committee Member

-   **Co-President,** *Biostatistics Student Organization, Johns Hopkins University,* 2022 -- 2024

-   **Biostatistics Department Representative,** *Mental Health Graduate Network, Johns Hopkins University,* 2021 -- 2024

-   **Mentoring Committee and Curriculum Committee Member,** *Biostatistics Student Organization, Johns Hopkins University,* 2020 -- 2024

-   **Team Captain,** *Varsity Women's Soccer, Johns Hopkins University,* 2019

-   **Assistant New Member Director,** *Phi Mu Gamma Tau Chapter, Johns Hopkins University,* 2019

-   **Captains Cohort Member,** *Blue Jays LEAD, Johns Hopkins University,* Spring 2019 -- 2020

## Community Memberships

-   [*American Statistical Association*](https://www.amstat.org/), 2022 — present

-   [*International Biometrics Society, Eastern North American Region*](https://www.enar.org/), 2022 -– present
